#!/usr/bin/env sh

echo 'Bem vindo aos meus resumos que algoritimo queres testar? 
(Lembrando de instalar previamente as dependencias para executar)
1 - Algoritimos
2 - ciOpsNotes
3 - dataScienceNotes
4 - linguagens
5 - webDevNotes'

echo ''

echo 'Insira o valor acima: '
read escolha1

if [ escolha1 == 1 ]
then
    echo 'foi'
else 
fi